seed: 42

data:
  val_size: 0.1

data_path: data/augmented

augment:
  n_per_image: 2
  max_per_class: 6000

model:
  type: resnet18        # logreg | simple_cnn | resnet18

train:
  epochs: 1
  batch_size: 64
  lr: 0.01
  weight_decay: 0.0
